"""The Finance desk's front page (TASK_QUEUE TQ-27, owner request 2026-08-25;
docs/SPEC_RECONCILIATION.md §77).

A market front page in the shape of a finance portal — tickers, movers,
headlines — assembled from **this system's own simulated world**, never from a
real market.

## Everything here is SIMULATED, and says so

The owner's instruction was to simulate some news for now, with a group of
newspaper agents owning this page later. That makes honesty the whole design
constraint, because a finance page is the single most dangerous place in this
system to blur synthetic and real: someone reading a price here must never be
able to mistake it for a quote, and a headline must never be mistakable for
news. So:

- Prices come from stored `option_chain` observations — the underlying quotes
  the Market Data Simulation Engine generated (addendum 25) — and carry the
  provenance that produced them.
- Headlines are generated placeholders, flagged `placeholder: true`, and the
  payload says in as many words that newspaper agents do not exist yet.
- Nothing here is, or may be presented as, investment advice. The COO's
  system prompt carries the same rule for anything it reads off this desk.

## No market data is a fact, not an empty page

With no mission ever run there are no prices, and the desk says that and names
what would produce them. An empty table would read as "the market is quiet",
which would be a lie about a market that does not exist.
"""

from __future__ import annotations

import random

from backend import observations as observation_store
from backend import reference_data
from backend.db import Database

# Flagged on every payload this module returns. The console renders it as a
# banner; the COO's prompt is told to treat it as synthetic. One constant so
# the two cannot drift into disagreeing about what is real.
SIMULATED_NOTICE = (
    "SIMULATED — every price, move and headline on this desk is generated by this "
    "system's own Market Data Simulation Engine (addendum 25) for training. None of it "
    "is real market data, and none of it is investment advice."
)

# Placeholder headlines until newspaper agents write them. Deliberately about
# the *simulated* world's own mechanics rather than plausible real-world
# events - a fake headline about a real company is exactly the thing that
# should never leave this file.
_HEADLINE_TEMPLATES = (
    ("Synthetic session opens with {symbol} carrying the widest option spreads", "markets"),
    ("Parity holds across {n} focus names as the simulated ladder reprices", "derivatives"),
    ("{symbol} option chain shows the steepest generated skew of the session", "derivatives"),
    ("Simulated borrow costs keep the reversal leg unprofitable in {symbol}", "financing"),
    ("Training world regenerates: {n} focus assets repriced from the same seed", "markets"),
    ("Calendar spreads in {symbol} stay inside the executable band", "derivatives"),
    ("No arbitrage surfaced this cycle — the quiet session is the control", "markets"),
)


def _latest_underlying(conn: Database, entity_id: str) -> dict | None:
    """The most recent simulated underlying quote for an entity, from the
    option_chain observations the world stores. Returns None when the world
    has never been generated for it - which the caller reports rather than
    hides."""
    rows = observation_store.replay(conn, entity_id, "option_chain")
    if not rows:
        return None
    latest = rows[-1]
    payload = latest.payload
    underlying = payload.get("underlying") or {}
    bid, ask = underlying.get("bid"), underlying.get("ask")
    if bid is None or ask is None:
        return None
    return {
        "bid": bid,
        "ask": ask,
        # The mid is shown as a *display* price only. Every detector in this
        # system refuses to trade on a mid (addendum 27's opening rule), and
        # the console labels this column accordingly.
        "display_price": round((bid + ask) / 2, 2),
        "spread": round(ask - bid, 4),
        "as_of": payload.get("as_of") or latest.observed_at,
        "source": latest.provenance.source,
        "run_id": latest.provenance.run_id,
        "observations_held": len(rows),
    }


def _session_move(seed_text: str, price: float) -> dict:
    """A generated session move for display.

    Seeded from the symbol so a refresh does not reshuffle the board every two
    seconds - a front page whose numbers danced at random would be lively and
    useless. It changes when the world does, not when the page polls."""
    rng = random.Random(f"session-move:{seed_text}")
    pct = round(rng.uniform(-3.2, 3.2), 2)
    return {
        "change_pct": pct,
        "change": round(price * pct / 100, 2),
        "direction": "up" if pct > 0 else ("down" if pct < 0 else "flat"),
    }


def headlines(conn: Database, symbols: list[str], *, count: int = 6) -> list[dict]:
    """Placeholder front-page headlines, every one flagged as such.

    Seeded from the focus universe so the page is stable between polls and
    changes when the world does."""
    rng = random.Random(f"headlines:{','.join(sorted(symbols))}")
    chosen = rng.sample(_HEADLINE_TEMPLATES, k=min(count, len(_HEADLINE_TEMPLATES)))
    out = []
    for template, section in chosen:
        symbol = rng.choice(symbols) if symbols else "the focus universe"
        out.append({
            "headline": template.format(symbol=symbol, n=len(symbols)),
            "section": section,
            "placeholder": True,
        })
    return out


def front_page(conn: Database) -> dict:
    """The whole Finance desk in one read.

    Reports absence honestly: no focus assets, or a world never generated,
    each say so and name what would change it."""
    assets = reference_data.list_focus_assets(conn)
    if not assets:
        return {
            "simulated": True,
            "notice": SIMULATED_NOTICE,
            "available": False,
            "reason": "No focus assets are certified yet. The Reference Data Engine "
                      "populates them at startup.",
            "tickers": [], "movers": {"gainers": [], "losers": []}, "headlines": [],
        }

    tickers, priced = [], 0
    for asset in assets:
        symbol = asset["primary_identifier"]
        quote = _latest_underlying(conn, asset["entity_id"])
        row = {"symbol": symbol, "entity_id": asset["entity_id"]}
        if quote is None:
            row.update({"priced": False, "note": "no simulated market generated yet"})
        else:
            priced += 1
            row.update({"priced": True, **quote, **_session_move(symbol, quote["display_price"])})
        tickers.append(row)

    with_prices = [t for t in tickers if t.get("priced")]
    ranked = sorted(with_prices, key=lambda t: t["change_pct"], reverse=True)
    symbols = [t["symbol"] for t in tickers]

    # A gainer has to have gained. Slicing the ranking from both ends is the
    # obvious way to write this and it is wrong twice over: with a small
    # universe every asset lands in *both* lists, and on a down session the
    # "gainers" are simply the assets that fell least. Either way the desk
    # labels a decliner a gainer, which is the one thing a page about money
    # must never do - and it is a label the reader has no way to check without
    # reading the sign underneath it.
    #
    # An empty list is the honest answer when nothing rose, and the console
    # says so rather than padding the row.
    gainers = [t for t in ranked if t["change_pct"] > 0][:5]
    losers = [t for t in reversed(ranked) if t["change_pct"] < 0][:5]

    return {
        "simulated": True,
        "notice": SIMULATED_NOTICE,
        "available": True,
        "universe_size": len(assets),
        "priced_count": priced,
        "unpriced_note": (
            None if priced == len(assets)
            else f"{len(assets) - priced} of {len(assets)} focus assets have no simulated "
                 "market yet — run a mission (Simulation desk) to generate one."
        ),
        "tickers": tickers,
        "movers": {"gainers": gainers, "losers": losers},
        "headlines": headlines(conn, symbols),
        "headlines_note": "Placeholder headlines. A group of newspaper agents will write this "
                          "page later; until they exist, these are generated from the "
                          "simulated world's own mechanics and are marked as placeholders.",
    }
